OpenIPSL/OpenIPSL

OpenIPSL/Electrical/Machines/PSSE/GENROE/GENROE.mo, OpenIPSL/Electrical/Machines/PSSE/GENROE/package.mo, OpenIPSL/Electrical/Machines/PSSE/GENROU/GENROU.mo, OpenIPSL/Electrical/Machines/PSSE/GENROU/package.mo, OpenIPSL/Electrical/Machines/PSSE/GENSAE/GENSAE.mo, OpenIPSL/Electrical/Machines/PSSE/GENSAE/package.mo, OpenIPSL/Electrical/Machines/PSSE/GENSAL/GENSAL.mo, OpenIPSL/Electrical/Machines/PSSE/GENSAL/package.mo
=> Fixing the initialisation issue in OpenModelica for all of the generators

.travis.yml, CI/changeUser.sh, CI/runTests.py, runTests.py
Continuous Integration is implemented with Travis and Docker. 
When something is committed, Travis pulls an image from the SmarTS Lab repository at Docker Hub. This image has OpenModelica and OMPython installed. When the image is pulled, Travis creates a container and runs the shell script changeUser. 
The script changeUser adds a new username "smartslab" to the container and logs in as that user. This is done because the OMC cannot be run under root. Also, this script runs a python script (runTests.py) which recursively generates a list of models in the library, checks them and prints out results of checks.
=> Continuous Integration

OpenIPSL/Electrical/Sensors/PwVoltage.mo, OpenIPSL/Electrical/Sensors/package.mo, OpenIPSL/Electrical/Sensors/package.order, OpenIPSL/Electrical/package.order
Add voltage sensors back to the library because it is used by SVC model.
=> Add PwVoltage model back to the library

OpenIPSL/Electrical/Branches/PwLine.mo
See #55 for Description of the problem
A possible fix is to use the `Complex(0)` command to create a null
complex
=> Update PwLine for JModelica compatibility

README.md
=> Updating links and text

OpenIPSL/Electrical/Controls/package.order, OpenIPSL/Examples/Controls/package.order
=> Fix package.order for CGMES

README.md
=> Changing some wiki links 

OpenIPSL/Electrical/Events/PwFault.mo
Jmodelica is very strict about equality statements, I changed the ==0
statement to <eps and also changed ground to Boolean
=> Fix PwFault for Jmodelica

OpenIPSL/Electrical/Buses/Bus.mo
The wrong variables were used in the dynamic select
=> Fix Bus Display variables

OpenIPSL/Electrical/Buses/Bus.mo
V_0 and Angle0 were already defined in pfComponent (Jmodelica complained)
=> Fix Bus that contained double parameters

ApplicationExamples/OpenCPSD5d3B/Breakers/Breaker.mo, ApplicationExamples/OpenCPSD5d3B/Generators/G1.mo, ApplicationExamples/OpenCPSD5d3B/Generators/G2.mo, ApplicationExamples/OpenCPSD5d3B/Network.mo, ApplicationExamples/OpenCPSD5d3B/Network_Expanded.mo, ApplicationExamples/OpenCPSD5d3B/Network_Expanded_Noise.mo, ApplicationExamples/OpenCPSD5d3B/NoiseInjections/BaseClass.mo, ApplicationExamples/OpenCPSD5d3B/package.mo, CI/runTests.py
Since the connector PwPin was moved to another package and the models were built with the old version of the library, the CI was ofc complaining. It will not be possible to merge the PR until #105 is fixed.
=> Updates of PwPin references 

README.md
I have added explanatory text about the documentation, where to find tutorials and to download related MSc thesis.
=> Mods to Documentation Info

OpenIPSL/Electrical/Controls/PSSE/ES/IEEET1.mo
Code line removal based on suggestion of @tinrabuzin to fix issue #116
=> Changes applied to the IEEET1 model to fix the translation error

OpenIPSL/Electrical/Sensors/PwVoltage.mo, OpenIPSL/Examples/Machines/PSSE/GENROU.mo, OpenIPSL/Examples/Machines/PSSE/GENSAE.mo, OpenIPSL/Examples/Machines/PSSE/GENSAL.mo
Fixed error in PwVoltage, corrected models and descriptions in the GENROU, GENSAE and GENSAL examples
=> Small fixes to Examples and to the PwVoltage sensor.

OpenIPSL/Electrical/Machines/PSSE/BaseClasses/baseMachine.mo
Fixes the misplaced annotations in Icon layer for PSSE generators.
=> Fix to issue #114

ApplicationExamples/AKD/Copyright.mo, ApplicationExamples/IEEE14/Copyright.mo, ApplicationExamples/IEEE9/Copyright.mo, ApplicationExamples/KundurSMIB/Copyright.mo, ApplicationExamples/N44/Copyright.mo, ApplicationExamples/Namsskogan_Grid/Copyright.mo, ApplicationExamples/OpenCPSD5d3B/Copyright.mo, ApplicationExamples/PSAT_Systems/Copyright.mo, ApplicationExamples/SevenBus/Copyright.mo, ApplicationExamples/TwoAreas/Copyright.mo, ApplicationExamples/_Tutorial/Tutorial/Copyright.mo, OpenIPSL/Copyright.mo, README.md
Preparing for the transfer of the repository
=> Modifying Copyright for Luigi

ApplicationExamples/_Tutorial/Tutorial/Example_1/Example_1.mo, ApplicationExamples/_Tutorial/Tutorial/Example_2/Example_2.mo, OpenIPSL/Electrical/Machines/PSAT/Order6.mo
Angles should be given in degrees, not rads.
See #160
=> Fix error in Tutorial:

.gitignore, ApplicationExamples/KundurSMIB/Generation_Groups/Generator.mo, ApplicationExamples/KundurSMIB/Generation_Groups/Generator_AVR.mo, ApplicationExamples/KundurSMIB/Generation_Groups/Generator_AVR_PSS.mo, ApplicationExamples/KundurSMIB/Generation_Groups/package.mo, ApplicationExamples/KundurSMIB/SMIB.mo, ApplicationExamples/KundurSMIB/SMIB_AVR.mo, ApplicationExamples/KundurSMIB/SMIB_AVR_PSS.mo, ApplicationExamples/KundurSMIB/SMIB_Partial.mo, ApplicationExamples/KundurSMIB/package.mo
Also updated the contact info and some visual improvements.
=> Updating the KundurSMIB package to make use of the Generator interface

OpenIPSL/Electrical/Controls/PSAT/TG/TGTypeI.mo, OpenIPSL/Electrical/Controls/PSAT/TG/TGTypeIII.mo, OpenIPSL/Electrical/Controls/PSAT/TG/TGTypeIV.mo, OpenIPSL/Electrical/Controls/PSAT/TG/TGTypeV.mo, OpenIPSL/Electrical/Controls/PSAT/TG/TGTypeVI.mo, OpenIPSL/Electrical/Controls/PSAT/TG/TGtypeII.mo, OpenIPSL/Electrical/Controls/PSSE/TG/GAST.mo, OpenIPSL/Electrical/Controls/PSSE/TG/GGOV1/GGOV1.mo, OpenIPSL/Electrical/Controls/PSSE/TG/HYGOV.mo, OpenIPSL/Electrical/Controls/PSSE/TG/IEEEG1.mo, OpenIPSL/Electrical/Controls/PSSE/TG/IEESGO.mo, OpenIPSL/Electrical/Controls/PSSE/TG/TGOV1.mo, OpenIPSL/Examples/Controls/CGMES/ES/ExcSEXS.mo, OpenIPSL/Examples/Controls/CGMES/ES/package.mo, OpenIPSL/Examples/Controls/CGMES/package.mo, OpenIPSL/Examples/Controls/PSSE/TG/GAST.mo
Fixes based on master branch of  @marcelofcastro
=> Fixing governor models 

OpenIPSL/Examples/SMIBpartial2.mo
Based on the master branch of @marcelofcastro
=> Fix Banks models

OpenIPSL/Examples/Controls/PSSE/ES/IEEET2.mo
Based on master branch of @marcelofcastro
=> Fix exciter models

OpenIPSL/Electrical/Controls/PSSE/ES/ESST4B.mo
This fixes #150.
Best to wait with merging until #228 is merged.
=> Correct calculation of I_T in ESSTB4

OpenIPSL/Electrical/Machines/PSSE/GENCLS.mo, OpenIPSL/Electrical/Solar/KTH/Auxiliary/Terminator.mo, OpenIPSL/Electrical/SystemBase.mo, OpenIPSL/NonElectrical/Continuous/RampTrackingFilter.mo
Fixes #210 by giving a default start value with dimension 1
=>  Fix Terminator dimension warning

.travis.yml, CI/CITests.py, CI/syntaxCheck.py, Dockerfile
I'm using the PR in order to fix the CI setup again.
Fixes #220
=> Fix the CI setup

OpenIPSL/Electrical/Machines/PSSE/GENCLS.mo, OpenIPSL/Examples/Machines/PSSE/GENCLS.mo
Fixes #270 by improving the documentation and also opening the parameters that were locked before.
=> Improves documentation of GENCLS and unlocks parameters

OpenIPSL/UsersGuide/Contact.mo, OpenIPSL/UsersGuide/GettingStarted.mo, OpenIPSL/UsersGuide/Overview.mo, OpenIPSL/UsersGuide/Publications.mo, OpenIPSL/UsersGuide/ReleaseNotes/v100.mo, OpenIPSL/UsersGuide/ReleaseNotes/v150.mo, OpenIPSL/UsersGuide/Testing.mo, OpenIPSL/package.mo
As preparation of v2.0.0 release. I have not yet updated the v2.0.0 release notes themselves since this I like to do as the very last thing.
=> Update the User's Guide

OpenIPSL/Electrical/Sensors/SoftPMU.mo, OpenIPSL/NonElectrical/Nonlinear/FrequencyCalc.mo, OpenIPSL/NonElectrical/Nonlinear/package.order
This PR is supposed to fix soft PMU implementation by fixing the frequency estimate calculation and other small details.
When merged, this PR will close issue #173
=> Fixing soft PMU implementation

OpenIPSL/Resources/scripts/ConvertOpenIPSL_from_1.5.0_to_2.0.0.mos, OpenIPSL/UsersGuide/ReleaseNotes/v200.mo, OpenIPSL/package.mo, README.md
closes #247 
@marcelofcastro and @lvanfretti : Have a look if you think that I got everything caught in the release notes. I don't think we need to update the readme itself but rather extend the release notes on the GitHub Releases page once this is accepted.
=> Adding the release notes

OpenIPSL/Electrical/Controls/PSSE/ES/ESST4B.mo, OpenIPSL/Electrical/Machines/PSSE/GENROE.mo, OpenIPSL/Electrical/Machines/PSSE/GENROU.mo, OpenIPSL/Electrical/Machines/PSSE/GENSAE.mo
https://github.com/OpenIPSL/OpenIPSL/issues/301
=> 'abs' function not properly converted to MSL 4.0.0

OpenIPSL/Electrical/Branches/PSAT/TwoWindingTransformer.mo, OpenIPSL/Electrical/Controls/PSSE/PSS/IEEEST.mo, OpenIPSL/Electrical/Machines/PSAT/Order4.mo
Closes #308.
See https://github.com/modelica/ModelicaStandardLibrary/commit/0b581271c0c7153ffb5cf4a8831a493e8a757975 for an identical fix within MSL.
=> Avoid equality on Real variables

OpenIPSL/Electrical/Sources/VoltageSourceReImInput.mo, OpenIPSL/Electrical/Sources/package.mo, OpenIPSL/Electrical/Sources/package.order, OpenIPSL/Electrical/package.order, OpenIPSL/Tests/Sources/VoltageSourceReImInputConstant.mo, OpenIPSL/Tests/Sources/VoltageSourceReImInputVaryImag.mo, OpenIPSL/Tests/Sources/VoltageSourceReImInputVaryReal.mo, OpenIPSL/Tests/Sources/VoltageSourceReImInputVaryRealAndImag.mo, OpenIPSL/Tests/Sources/package.mo, OpenIPSL/Tests/Sources/package.order, OpenIPSL/Tests/package.order
Attempting to make the commit from fork.
Cosmetic update inheriting sources icon from MSL.
=> Ideal Voltage Source

OpenIPSL/NonElectrical/Logical/NegCurLogic.mo
Meant to apply to #315 . OpenIPSL.Tests.Controls.PSSE.ES.SCRX builds and runs in WSM 13.2. Previously it didn't.
=> Invalid == on Reals NegCurLogic

OpenIPSL/Electrical/Controls/PSSE/PSS/IEEEST.mo
Meant to apply to #315 .  OpenIPSL.Tests.Controls.PSSE.PSS.IEEEST builds and runs in WSM 13.2.
=> Invalid == on Reals IEEEST

OpenIPSL/Electrical/Solar/PowerFactory/DIgSILENT/DCBusBar.mo, OpenIPSL/Electrical/Solar/PowerFactory/General/ElmGenstat.mo
Fixes #317 by using protected connectors instead of helping variables.
=> Convert internal variable to connector

OpenIPSL/Electrical/Controls/PSSE/ES/BaseClasses/invFEX.mo
=> Remove cyclical dependency on function input
