- Application Examples/SevenBus/Generators/G1.mo
- Application Examples/SevenBus/Generators/G2.mo
- Application Examples/SevenBus/Generators/G3.mo
Removing connect equations that are no longer needed from the generator groups.
> Updating the SevenBus example

- OpenIPSL/Electrical/Controls/PSSE/PSS/IEEEST.mo
- Added default values for parameters A_x to avoid undefined size of arrays
- Added each operator at the definition of array parameters to avoid warning that the fixed=false doesn't apply to the whole array
> Updating IEEEST

- OpenIPSL/Electrical/Controls/PSAT/AVR/AVRtypeIII.mo
- OpenIPSL/Examples/Machines/PSAT/Order3test2_AVR.mo
- OpenIPSL/Examples/Machines/PSAT/Order4test2_AVR.mo
- Removed parameters s0, v0 and vref from the AVR model
- Updated examples using this AVR model
> Updating PSAT AVR Type III to remove initialization parameters

- .gitignore
- Support/addCopyright.py
- Support/copyrightStatement
Adding /Support folder to contain a set of script to assist the release of the library. The first script is to automate the update of the copyright information. 
The script is supposedly working but introduces errors in the syntax of the files. See #47 
Because of that the PR is sent to a separate branch waiting for more info from OM.
> Release support

- OpenIPSL/package.mo
Dymola 2016FD01 and onwards are finally displaying bitmaps correctly with the correct {{bottomleft},{topright}} coordinates. They did not before which means Icons added and saved with older versions will be saved incorrectly. This PR fixes the coordinates.
> Fixing the rotation of the package logo

- README.md
Updated the documentation section, to point to the links in the readthedocs io.
The first link did not display the http://openipsl.readthedocs.io/ correctly.
I erased the old information about the application guide and test networks as it is not longer relevant.
> Documentation links

- OpenIPSL/Electrical/Branches/PwLine.mo
- OpenIPSL/Electrical/Buses/Bus.mo
- OpenIPSL/Electrical/Buses/InfiniteBus.mo
- OpenIPSL/Interfaces/Generator.mo
At the same time add the Dymola specific fallback since dymola does not support `checkbox` yet but only its own  (`__Dymola_`)`checkBox`
> Fixing the spelling of the standard "checkbox" annoation

- OpenIPSL/Electrical/Branches/PwLine.mo
- OpenIPSL/Electrical/Buses/Bus.mo
- OpenIPSL/Electrical/Buses/InfiniteBus.mo
- OpenIPSL/Interfaces/Generator.mo
Turns out there is a typo in the Specification and the annotation should correctly be called "checkBox" (like the old Dymola annotation). This will be fixed in OMEdit soon. So all for nothing unfortunately. 
https://trac.modelica.org/Modelica/ticket/1770
This reverts_ 7d2d1a372639ea1720d983f05b2da0e2309bb190
> Reverting the fix of the checkbox

- OpenIPSL/Electrical/SystemBase.mo
This saves also one step in the tutorial ;-)
> Add default prefixes definition for SystemBase

- OpenIPSL/Electrical/Machines/PSAT/BaseClasses/baseMachine.mo
- OpenIPSL/Electrical/Machines/PSAT/Order2.mo
- OpenIPSL/Electrical/Machines/PSAT/Order3.mo
- OpenIPSL/Electrical/Machines/PSAT/Order4.mo
- OpenIPSL/Electrical/Machines/PSAT/Order5_Type1.mo
- OpenIPSL/Electrical/Machines/PSAT/Order5_Type2.mo
- OpenIPSL/Electrical/Machines/PSAT/Order6.mo
This is something that came up during today's workshop. Basically some of the connectors were not displayed correctly because of an empty `iconTransformation` annotation. At the same time I've cleaned up the annotations and texts. Also getting rid of the font specifier that is totally superfluous (especially since Arial is not a free font type).
> Fixing the PSAT machine connector annotations

- OpenIPSL/Electrical/Wind/PSSE/WT4G/WT4G1.mo
./OpenIPSL/Examples/Wind/PSSE/WT4G/WT4G1_WT4E1.mo will not run when setting:
``Modelica.Blocks.Math.Feedback Iperr(y(start=0, fixed=true));``
Changed to ``fixed=false`` results on valid simulation result under Dymola 2018.
> WT4G1 Initial Condition breaks Simulation

- OpenIPSL/Electrical/Controls/PSAT/OEL/FieldCurrent.mo
- OpenIPSL/Electrical/Controls/PSAT/OEL/OEL.mo
- OpenIPSL/Electrical/Machines/PSAT/BaseClasses/baseMachine.mo
- OpenIPSL/Electrical/Machines/PSAT/Order2.mo
- OpenIPSL/Examples/Controls/PSAT/OEL/AVRTypeII_OEL_Test.mo
#PSAT machine model 2: Corrects a nasty bug of commit 4eb03d4 (which made corresponding examples not runnable) as well as some old problems of different bases of all PSAT machine models, which were mishandled since very early commits. Also, fixes the PSAT OEL to have correct behavior.
> Fixes PSAT machines handling of bases and PSAT OEL

- OpenIPSL/NonElectrical/Continuous/DerivativeLag.mo
quick fix of a typo. More work would be needed to document properly all the transfer function blocks (e.g. what is this time constant `T`), but that will be for another day...
> fix typo in DerivativeLag

- OpenIPSL/Electrical/Machines/PSSE/GENCLS.mo
- OpenIPSL/Examples/SMIBpartial.mo
I edited the start value of the GENCLS machine base power rating model to 100e6 as a start value (when you simulate it there is a translation warning about this). Then I edited the SMIBpartial model to have this as a starting value. I also used sublime text rather than dymola in order to make sure that graphics would not be changed or messed with.
> Machine base power rating change

- OpenIPSL/Examples/Branches/PSAT/TwoWindingTransformer_Test.mo
Having the infinite bus connected in parallel with the generator in the example simply doesn't make sense. So either have the infinite bus or the generator. I've chosen to keep the generator.
> Removing the infinite bus from the example

- OpenIPSL/Electrical/Machines/PSAT/BaseClasses/baseMachine.mo
Those hard coded lines make it impossible to change the start speed of the generator. Something needed in run-up tests etc.  In addition, delta was initialised twice.
> Remove hard coded and doubly defined start values for w and delta

- OpenIPSL/Electrical/Controls/PSAT/AVR/AVRTypeI.mo
- OpenIPSL/Electrical/Controls/PSAT/AVR/AVRTypeII.mo
- OpenIPSL/Electrical/Controls/PSAT/AVR/AVRtypeIII.mo
- OpenIPSL/UsersGuide/References.mo
Fixes #164: Adds a warning and also reference to F. Milano's book
> Explains the PSAT AVR models mix up

- OpenIPSL/Electrical/Buses/Bus.mo
- OpenIPSL/Electrical/Machines/PSSE/GENCLS.mo
- OpenIPSL/Examples/BaseClasses/SMIB.mo
This update should fix some initialization problems with SMIB system and the over-specified equation for omega. This might address issues #170 and #229 
(fixes #170 and fixes #229)
> Fix gencls

- OpenIPSL/Electrical/Machines/PSSE/BaseClasses/baseMachine.mo
- OpenIPSL/Electrical/Machines/PSSE/GENROE.mo
- OpenIPSL/Electrical/Machines/PSSE/GENROU.mo
- OpenIPSL/Electrical/Machines/PSSE/GENSAE.mo
- OpenIPSL/Electrical/Machines/PSSE/GENSAL.mo
This allows the generator models to be used in application where start speeds other than 1 pu are required (e.g., run up and synchronisation of a generator)
> Add an initial speed deviation and remove superfluous initial equationns

- OpenIPSL/Types.mo
Noticed a small mismatch in the display units for `ReactivePower` under `OpenIPSL.Types`. Changed to `Mvar`
> Corrected display units of reactive power

- OpenIPSL/Electrical/Controls/PSSE/ES/ESAC1A.mo
- OpenIPSL/Electrical/Controls/PSSE/ES/ESAC2A.mo
- OpenIPSL/Electrical/Controls/PSSE/ES/ESDC1A.mo
- OpenIPSL/Electrical/Controls/PSSE/ES/ESDC2A.mo
- OpenIPSL/Electrical/Controls/PSSE/ES/ESST1A.mo
- OpenIPSL/Electrical/Controls/PSSE/ES/ESST4B.mo
- OpenIPSL/Electrical/Controls/PSSE/ES/EXAC2.mo
- OpenIPSL/Electrical/Controls/PSSE/ES/ST5B.mo
- OpenIPSL/Electrical/Controls/PSSE/ES/URST5T.mo
- OpenIPSL/Electrical/Controls/PSSE/TG/GAST.mo
- OpenIPSL/NonElectrical/Logical/HV_GATE.mo
- OpenIPSL/NonElectrical/Logical/LV_GATE.mo
- OpenIPSL/Resources/Scripts/ConvertOpenIPSL_from_1.5.0_to_2.0.0.mos
This keeps the visual appearance but at the same time extends the Min and Max blocks from the MSL. 
Conversion script takes care of the rename of the connector names.
> Replaces custom LV and HV gate definitions with MSL blocks

- OpenIPSL/NonElectrical/Functions/SE.mo
This eliminates many errors when simulating the CIM translated IEEE14 in WSM 13.2 because of it's effect on PSSE.GENROU.
> Avoid equality on Real variables in SE Non-electrical function

- OpenIPSL/Electrical/Branches/PSAT/TwoWindingTransformer.mo
- OpenIPSL/Electrical/Branches/PwLine.mo
- OpenIPSL/Electrical/Loads/PSAT/BaseClasses/baseLoad.mo
- OpenIPSL/Examples/IEEE14/Generation_Groups/GroupBus1.mo
- OpenIPSL/Examples/IEEE14/Generation_Groups/GroupBus2.mo
- OpenIPSL/Examples/IEEE14/Generation_Groups/GroupBus3.mo
- OpenIPSL/Examples/IEEE14/Generation_Groups/GroupBus6.mo
- OpenIPSL/Examples/IEEE14/Generation_Groups/GroupBus8.mo
- OpenIPSL/Examples/IEEE14/IEEE_14_Buses.mo
- OpenIPSL/Interfaces/PwPin_n.mo
- OpenIPSL/Interfaces/PwPin_p.mo
- OpenIPSL/Interfaces/package.order
I've implemented some graphical enhancements to the library.
Mainly:
1. enlarged the text boxes so that more space is mada available to theri content. The previous text boxes caused nearly always the names to be truncated with ellipises
2. visually differentiated positive and negative pins in lines and transformers. Now, in compliance with the de-facto standard of Modelica Standard library, the positive pins are blue-fitted, the negative ones white fitted..
More details are available in the comments of individual commit composing thsi PR.
> Graphical enhancements of line model and IEEE14 example

- .CI/check_deprecated_line_color.py
Previously, a Text.lineColor annotation was not detected, if there was a closing parenthesis (within a quoted Text.textString annotation), e.g.
```mo
Text(extent={{-100,80},{-80,60}}, textString="1)", lineColor={0,0,255})
```
> Fix regex to optionally ignore quoted strings when checking for deprecated Text.lineColor annotation

- OpenIPSL/Electrical/Sources/SourceBehindImpedance/BaseClasses/baseVoltageSource.mo
- OpenIPSL/Electrical/Sources/SourceBehindImpedance/VoltageSources/VSourceIO.mo
- OpenIPSL/Tests/Sources/SourcesBehindImpedance/VSourceIO.mo
- OpenIPSL/Tests/Sources/SourcesBehindImpedance/VSourceIO_StartFromExternal_using_RealExpression.mo
- OpenIPSL/Tests/Sources/SourcesBehindImpedance/VSourceIO_StartFromExternal_using_VSIO_outputs.mo
- OpenIPSL/Tests/Sources/SourcesBehindImpedance/package.order
Changes/Additions to components:
- Change to base class in order to move the outputs to more convenient location for wiring.
- Changed VSourceIO to provide 2 options. One that sets value of the voltage source starting from the value calculated internally (E0 and delta0) and another one that does not. This is needed to be able to link the control blocks of a grid forming converter, that needs to start from E0 and delta0 itself, similar to what is done with synch machines.
Changes to the Tests:
- Modified the VSourceIO to set the flag to "true", given the options above.
Additions:
- Added two examples of how the internally calculated E0 and delta0 need to be provided for adequate initialization.
> Adding input option to voltage source behind an impedance model

- OpenIPSL/package.mo
> remove bogus libraries AC7B and DC4B from the uses annotation

- OpenIPSL/Electrical/Controls/PSSE/PSS/IEE2ST.mo
- OpenIPSL/Electrical/Renewables/PSSE/ElectricalController/REECA1.mo
- OpenIPSL/Electrical/Renewables/PSSE/ElectricalController/REECB1.mo
- OpenIPSL/Electrical/Renewables/PSSE/ElectricalController/REECCU1.mo
- OpenIPSL/Electrical/Renewables/PSSE/PlantController/REPCA1.mo
Fixes #365 
Modify == to <0 or >0 on IEE2ST, REECA1, REECB1, REECCU1, and REPCA1. This applies to models and not functions such as SE or atan3.
> Update Reals IEE2ST, REECA1, REECB1, REECCU1, and REPCA1

- OpenIPSL/NonElectrical/Continuous/SimpleLag.mo
- OpenIPSL/NonElectrical/Continuous/SimpleLagLimVar.mo
This suggests evaluation of two parameters, which simplifies the initial equation systems.
For Wolfram System Modeler, this breaks apart some equation blocks sufficiently that these models can be built and simulated:
```
OpenIPSL.Tests.Controls.PSSE.ES.ST5B
OpenIPSL.Tests.Controls.PSSE.ES.ESST4B
OpenIPSL.Tests.Controls.PSSE.ES.EXST1
OpenIPSL.Examples.RaPIdExperiments.Mostar
OpenIPSL.Examples.DAEMode.SMIB_Examples.Example_1.Network3
OpenIPSL.Examples.SevenBus.Network
```
See #368.
> Parameter evaluation for simpler initial equation systems
